src/GridItem.vue, src/GridLayout.vue, src/ResponsiveGridLayout.vue
Now the listeners are removed on beforeDestroy.
=> Remove listeners beforeDestroy

src/GridItem.vue
=> Support user-defined selectors to ignore during drag/resize

src/GridLayout.vue
=> fixed #130

src/App.vue, src/GridItem.vue, src/GridLayout.vue
Fix https://github.com/jbaysolutions/vue-grid-layout/issues/121
=> Support colNum dynamic

src/App.vue, src/DOM.js, src/GridItem.vue, src/GridLayout.vue, src/ResponsiveGridLayout.vue
closes #193 and also adds some prep for #132.
=> abstract DOM related calls for initial SSR Support

README.md, package-lock.json, src/App.vue, src/components/GridLayout.vue, src/components/ResponsiveGridLayout.vue, src/helpers/responsiveUtils.js
updated to new structure and fixed Bug when adding or removing elements from grid 
Please have a look into it :)
_responsive is set via prop_
=> responsive v2

src/components/GridLayout.vue
https://github.com/jbaysolutions/vue-grid-layout/issues/284
=> Memory leak fixes #284

README.md
I have been working with this tool and it facilitates our life. Thanks for the support, our application can create an incredible dashboard thanks to you.
=> Add Data Providers to readme

package.json
Fixes: https://github.com/jbaysolutions/vue-grid-layout/issues/320.
=> bump interact to 1.5.3

README.md, src/components/GridItem.vue
Two minor changes to spelling and documentation.
=> Doc update fix spelling

src/components/GridLayout.vue
=> trigger layout-update when layout updated

src/components/GridItem.vue
=> Make margin reactive.

examples/07-prevent-collision.html, examples/08-responsive-predefined-layouts.html, examples/09-dynamic-add-remove.html, examples/09-dynamic-add-remove.js, src/App.vue
This PR adds Example 9 - Dynamic Add/Remove. 
A dynamic add button was added to App.vue.
A typo was corrected on Example 7.
=> Issue 448: Add Example 9 - Dynamic Add/Remove

website/docs/.vuepress/config.js, website/docs/zh/README.md, website/docs/zh/changelog/README.md, website/docs/zh/guide/01-basic.md, website/docs/zh/guide/02-events.md, website/docs/zh/guide/03-multiple-grids.md, website/docs/zh/guide/04-allow-ignore.md, website/docs/zh/guide/05-mirrored.md, website/docs/zh/guide/06-responsive.md, website/docs/zh/guide/07-prevent-collision.md, website/docs/zh/guide/08-responsive-predefined-layouts.md, website/docs/zh/guide/09-dynamic-add-remove.md, website/docs/zh/guide/10-drag-from-outside.md, website/docs/zh/guide/README.md, website/docs/zh/guide/auto-size.md, website/docs/zh/guide/events.md, website/docs/zh/guide/examples.md, website/docs/zh/guide/properties.md, website/docs/zh/guide/styling.md, website/docs/zh/guide/usage.md
The following link can see the final result：
https://ygj6.github.io/vue-grid-layout/
=> Add Chinese website documents.

README-zh_CN.md, website/docs/guide/properties.md
Part of the parameter description is incomplete, supplementary explanation.
=> Supplementary parameter description.

src/components/GridItem.vue
=> Preserver aspect ratio

website/docs/zh/changelog/README.md
Fix #542:Update the Chinese documentation with the changelog for 2.3.12 and the new GridItem preserveAspectRatio prop.
=> Fix issue 542.

rollup.config.js
#521 is resolved by adjusting the plug-in sequence.
=> Fix issue 521.

src/components/GridLayout.vue
=> Fix issue 529:Grid responsive does not work in vue3.

.github/workflows/vuepress-deploy.yml, babel.config.js, jest.config.js, package.json, test/unit/GridItem.spec.js
I first integrate the test framework into the project, and then try to supplement the test cases, 
and at the same time, I can get others to perfect it. What do you think?
PS：Related issue #534
=> Add `vue-test-utils` test framework.

src/helpers/utils.js
move item to compareWith bottom. #676
=> fix unexpected layout beheavior

src/App.vue
Hi, this PR adds a checkbox in the test `App.vue` allowing to change the `verticalCompact` prop.
=> Add compact in test app

src/helpers/utils.js
Reverts jbaysolutions/vue-grid-layout#677
=> Revert "fix unexpected layout beheavior"

test/unit/utils.spec.js
Add testcase for utils, learn from react-grid-layout.
=> Add testcase for utils

website/docs/zh/guide/11-bounded.md
=> docs(README-zh_CN.md): add bouned title explain by zh_CN
